'use client'

import React from "react";
import { Clock, MapPin, Users, Car, DoorOpen, XCircle, UserCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { cn, compareProfilesByHierarchy, canViewLeaveDetails } from "@/lib/utils";
import { format, isSameDay } from "date-fns";
import { typeLabels, statusLabels } from "../_lib/constants";
import { AvatarStack } from "@/components/ui/people-picker";
import { canCoordinateSharedResources } from "@/lib/permissions";
import RejectScheduleDialog from "./RejectScheduleDialog";

interface ScheduleCardProps {
  item: any;
  profile?: any;
  onSelect: (item: any) => void;
  onStatusUpdate: (id: string, status: string, reason?: string) => void | Promise<void>;
}

const statusBarColor: Record<string, string> = {
  pending: "bg-amber-500",
  approved: "bg-emerald-500",
  rejected: "bg-red-500",
  in_progress: "bg-blue-500",
  completed: "bg-slate-300",
};

export default React.memo(function ScheduleCard({ item, profile, onSelect, onStatusUpdate }: ScheduleCardProps) {
  const isCoordinator = canCoordinateSharedResources(profile);
  const [rejectOpen, setRejectOpen] = React.useState(false);
  const type = typeLabels[item.type] || typeLabels.meeting;
  const status = statusLabels[item.status] ?? { label: item.status ?? "Không rõ", color: "bg-slate-100 text-slate-500" };
  const isTrip = item.type === 'trip';
  const isRejected = item.status === 'rejected';
  const isOwnRejected = isRejected && profile?.id && item.created_by === profile.id;
  const sortedParticipants = [...(item.participants || [])].sort((a: any, b: any) => compareProfilesByHierarchy(a.profile, b.profile));
  const startTime = new Date(item.start_time);
  const endTime = new Date(item.end_time);
  const sameDay = isSameDay(startTime, endTime);
  const isAutoGeneratedEndTime = format(endTime, 'HH:mm') === '23:59';
  const showEndTime = item.status === 'completed' || !isAutoGeneratedEndTime;
  const barColor = statusBarColor[item.status] || "bg-slate-700";

  const isAllowedToView = canViewLeaveDetails(item, profile);
  const displayTitle = isAllowedToView ? item.title : `Nghỉ phép (${item.creator?.full_name || 'Cán bộ'})`;

  // Driver info from vehicle
  const driverName = item.driver?.full_name
    || (item.vehicle as any)?.default_driver?.full_name
    || null;
  const driverPhone = item.driver?.phone
    || (item.vehicle as any)?.default_driver?.phone
    || null;

  // Format time range
  const isOverdue = item.status === 'in_progress' && new Date() > endTime;
  const effectiveEnd = isOverdue ? new Date() : endTime;
  const timeRange = showEndTime
    ? sameDay
      ? `${format(startTime, 'HH:mm')} - ${format(effectiveEnd, 'HH:mm')}`
      : `${format(startTime, 'dd/MM HH:mm')} - ${format(effectiveEnd, 'dd/MM HH:mm')}`
    : `Từ ${format(startTime, sameDay ? 'HH:mm' : 'dd/MM HH:mm')}`;

  return (
    <Card className={cn(
      "rounded-2xl overflow-hidden border-none shadow-sm hover:shadow-xl active:scale-[0.98] transition-all duration-300 ease-in-out group relative",
      isTrip ? "hover:bg-amber-50/40" : "hover:bg-slate-50"
    )}>
      <CardContent className="p-0">
        <button
          type="button"
          className="absolute inset-0 w-full h-full cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/20 rounded-2xl z-0"
          onClick={() => onSelect(item)}
          aria-label={`Chi tiết lịch: ${displayTitle}`}
        />
        <div className="flex">
          {/* Left color bar — theo status, luôn cố định width */}
          <div className={cn("w-2 shrink-0", barColor)} />

          <div className="flex-1 p-4 space-y-3">
            {/* Hàng 1: Badge loại + Badge đặc biệt */}
            <div className="flex items-start justify-between">
              <div className="space-y-1.5 flex-1 min-w-0 pr-2">
                <div className="flex flex-wrap items-center gap-1.5 md:gap-2">
                  <Badge variant="outline" className={cn("text-xs font-semibold px-2.5 py-1 rounded-md whitespace-nowrap", type.color)}>
                    <type.icon className="w-3 h-3 mr-1 shrink-0" /> {type.label}
                  </Badge>
                  {item.use_vehicle && item.status === 'pending' && (
                    <Badge className="bg-amber-50 text-amber-700 border border-amber-100 font-semibold text-xs px-2.5 py-1 rounded-md">
                      <Car className="w-2.5 h-2.5 mr-0.5 shrink-0" /> {item.vehicle_id ? 'Chờ duyệt xe' : 'Chưa gán xe'}
                    </Badge>
                  )}
                  {isOwnRejected && (
                    <Badge className="bg-red-50 text-red-700 border border-red-200 font-semibold text-xs px-2.5 py-1 rounded-md">
                      <XCircle className="w-2.5 h-2.5 mr-0.5 shrink-0" /> Cần sửa
                    </Badge>
                  )}
                  <Badge className={cn("text-xs font-semibold px-2.5 py-1 rounded-md", status.color)}>
                    {status.label}
                  </Badge>
                </div>
                <h3 className="text-[17px] font-semibold text-slate-900 leading-snug pt-1.5 pb-0.5">{displayTitle}</h3>
              </div>
            </div>

            {/* Hàng 2: Giờ (gộp 1 dòng) + Participants */}
            <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5">
              <div className="flex items-center gap-2">
                <Clock className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                <span className="text-sm font-medium text-slate-700">{timeRange}</span>
              </div>
              {sortedParticipants.length > 0 && (
                <div className="flex items-center gap-2">
                  <Users className="w-3.5 h-3.5 text-slate-400 shrink-0" />
                  <AvatarStack
                    people={sortedParticipants.map((p: any) => ({
                      id: p.profile?.id ?? '',
                      full_name: p.profile?.full_name ?? null,
                      avatar_url: p.profile?.avatar_url ?? null,
                    }))}
                    max={4}
                    size="sm"
                  />
                </div>
              )}
            </div>

            {/* Hàng 3: Địa điểm / Xe + lái xe */}
            <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5">
              {item.room && (
                <div className="flex items-center gap-1.5">
                  <DoorOpen className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                  <span className="text-sm font-medium text-slate-600 truncate max-w-[160px]">{item.room.name}</span>
                </div>
              )}
              {item.vehicle && (
                <div className="flex items-center gap-1.5">
                  <Car className="w-3.5 h-3.5 text-amber-600 shrink-0" />
                  <span className="text-sm font-medium text-amber-700 truncate max-w-[160px]">
                    {(item.vehicle as any).name} · {(item.vehicle as any).plate_number}
                  </span>
                </div>
              )}
              {driverName && (
                <div className="flex items-center gap-1.5">
                  <UserCheck className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                  <span className="text-sm font-medium text-slate-600 truncate max-w-[180px]">
                    {driverName}{driverPhone ? ` · ${driverPhone}` : ''}
                  </span>
                </div>
              )}
              {!item.room && !item.vehicle && item.location && (
                <div className="flex items-center gap-1.5">
                  <MapPin className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                  <span className="text-sm font-medium text-slate-600 truncate max-w-[200px]">{item.location}</span>
                </div>
              )}
            </div>

            {/* Hàng 3.5: Người tạo — cho mọi lịch trừ leave (leave privacy) */}
            {!item.creator?.full_name ? null : item.type === 'leave' ? (
              <div className="flex items-center gap-1.5">
                <span className="text-xs text-slate-400 font-medium italic">
                  {item.created_by === profile?.id ? 'Bạn đã tạo' : `${item.creator.full_name} đã tạo`}
                </span>
              </div>
            ) : (
              <div className="flex items-center gap-1.5">
                <span className="text-xs text-slate-400 font-medium">
                  Người tạo: {item.creator.full_name}
                </span>
              </div>
            )}

            {/* Hàng 4: Action cho coordinator — chỉ cho pending không xe hoặc có xe đã gán (BGĐ case) */}
            {isCoordinator && item.status === 'pending' && (
              <div className="flex gap-2 pt-3 border-t border-slate-50 relative z-10">
                {item.use_vehicle && !item.vehicle_id ? (
                  <span className="text-xs font-medium text-amber-600 bg-amber-50 rounded-xl px-3 py-2 border border-amber-100 w-full text-center">
                    Mở để gán xe
                  </span>
                ) : (
                  <>
                    <Button size="sm"
                      onClick={(e) => { e.stopPropagation(); onStatusUpdate(item.id, 'approved'); }}
                      className="flex-1 bg-emerald-600 hover:bg-emerald-700 min-h-10 rounded-xl font-semibold text-sm shadow-sm px-4"
                    >Xác nhận</Button>
                    <Button size="sm" variant="outline"
                      onClick={(e) => { e.stopPropagation(); setRejectOpen(true); }}
                      className="flex-1 min-h-10 rounded-xl font-semibold text-sm border-red-200 text-red-600 hover:bg-red-50 hover:text-red-700 px-4"
                    >Từ chối</Button>
                  </>
                )}
              </div>
            )}
          </div>
        </div>
      </CardContent>

      <RejectScheduleDialog
        isOpen={rejectOpen}
        setIsOpen={setRejectOpen}
        scheduleTitle={item.title}
        onConfirm={async (reason) => { await onStatusUpdate(item.id, 'rejected', reason); }}
      />
    </Card>
  );
});
